remote_theme: pmarsceill/just-the-docs
title: fritz2-documentation

# Aux links for the upper right navigation
aux_links:
  "Home":
    - "//www.fritz2.dev"
  "Documentation":
    - "//www.docs.fritz2.dev/README.html/"
  "Examples":
    - "//www.examples.fritz2.dev"
  "Api":
    - "//www.api.fritz2.dev/dokka/fritz2"
  "Github":
  - "//www.github.com/jwstegemann/fritz2"