remote_theme: pmarsceill/just-the-docs
title: fritz2

# Aux links for the upper right navigation
aux_links:
  "Home":
    - "//www.fritz2.dev"
  "Documentation":
    - "//docs.fritz2.dev"
  "Examples":
    - "//www.fritz2.dev/examples.html"
  "Api":
    - "//api.fritz2.dev/fritz2"
  "Github":
  - "//www.github.com/jwstegemann/fritz2"

# Footer content appears at the bottom of every page's main content
footer_content: "Distributed by an MIT license."